# Generated by Django 5.1.1 on 2024-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicindex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['created_at'], 'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
        migrations.AddField(
            model_name='registration',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='security_question',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
