# Generated by Django 5.1.1 on 2024-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
