# Generated by Django 5.1.1 on 2024-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('music_file', models.FileField(upload_to='music/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
