# Generated by Django 5.1.1 on 2024-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('fear', 'Fear'), ('surprised', 'Surprised'), ('anger', 'Anger'), ('relax', 'Relax')], max_length=20),
        ),
    ]
