# Generated by Django 5.1.1 on 2024-10-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0006_musicgenre_musiclanguage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicGenre',
        ),
        migrations.DeleteModel(
            name='MusicLanguage',
        ),
    ]
