# Generated by Django 5.1.1 on 2024-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0009_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='mood',
            field=models.CharField(blank=True, choices=[('anger', 'Anger'), ('happy', 'Happy'), ('sad', 'Sad'), ('overjoyed', 'Overjoyed'), ('relax', 'Relax'), ('romance', 'Romance'), ('satisfaction', 'Satisfaction'), ('excitement', 'Excitement'), ('interest', 'Interest'), ('surprise', 'Surprise'), ('nostalgia', 'nostalgia')], max_length=20),
        ),
    ]
