# Generated by Django 5.1.1 on 2024-10-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0012_alter_music_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
    ]
