# Generated by Django 5.1.1 on 2024-11-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0014_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='mood',
            field=models.CharField(blank=True, choices=[('anger', 'Anger'), ('happy', 'Happy'), ('sad', 'Sad'), ('relax', 'Relax')], max_length=20),
        ),
    ]
